var searchData=
[
  ['p2g_558',['p2g',['../namespaceCajita.html#af35c1fd6167a736a6a78cf742c2d6251',1,'Cajita']]],
  ['packarray_559',['packArray',['../classCajita_1_1Halo.html#af9421d35f1b7e9de6f996779742493ea',1,'Cajita::Halo::packArray(const Kokkos::View&lt; char *, memory_space &gt; &amp;buffer, const Kokkos::View&lt; int **, memory_space &gt; &amp;steering, const int element_idx, const std::integral_constant&lt; std::size_t, 0 &gt;, const Cabana::ParameterPack&lt; ArrayViews... &gt; &amp;array_views)'],['../classCajita_1_1Halo.html#ae5b93e8998f49d1d0201cc90ac454aeb',1,'Cajita::Halo::packArray(const Kokkos::View&lt; char *, memory_space &gt; &amp;buffer, const Kokkos::View&lt; int **, memory_space &gt; &amp;steering, const int element_idx, const std::integral_constant&lt; std::size_t, N &gt;, const Cabana::ParameterPack&lt; ArrayViews... &gt; &amp;array_views)']]],
  ['packbuffer_560',['packBuffer',['../classCajita_1_1Halo.html#af6d7a80dc844926cfec98d70730682e0',1,'Cajita::Halo']]],
  ['packelement_561',['packElement',['../classCajita_1_1Halo.html#a69d63d32151d5377839488906d89f2c2',1,'Cajita::Halo::packElement(const Kokkos::View&lt; char *, memory_space &gt; &amp;buffer, const Kokkos::View&lt; int **, memory_space &gt; &amp;steering, const int element_idx, const ArrayView &amp;array_view)'],['../classCajita_1_1Halo.html#a63e0d4650d0db171a4c828a146b82aeb',1,'Cajita::Halo::packElement(const Kokkos::View&lt; char *, memory_space &gt; &amp;buffer, const Kokkos::View&lt; int **, memory_space &gt; &amp;steering, const int element_idx, const ArrayView &amp;array_view)']]],
  ['packtypeatindex_562',['PackTypeAtIndex',['../structCabana_1_1PackTypeAtIndex.html',1,'Cabana']]],
  ['parameterpack_563',['ParameterPack',['../structCabana_1_1ParameterPack.html',1,'Cabana']]],
  ['parameterpackelement_564',['ParameterPackElement',['../structCabana_1_1ParameterPackElement.html',1,'Cabana']]],
  ['particledynamicpartitionerworkloadmeasurer_565',['ParticleDynamicPartitionerWorkloadMeasurer',['../classCajita_1_1ParticleDynamicPartitionerWorkloadMeasurer.html',1,'Cajita::ParticleDynamicPartitionerWorkloadMeasurer&lt; ParticlePosViewType, ArrayType, CellUnit, CellPerTileDim, num_space_dim, Device &gt;'],['../classCajita_1_1ParticleDynamicPartitionerWorkloadMeasurer.html#afb8dd5a970da27d6fa1eab1f1cc48347',1,'Cajita::ParticleDynamicPartitionerWorkloadMeasurer::ParticleDynamicPartitionerWorkloadMeasurer()']]],
  ['particlegridmigrate_566',['particleGridMigrate',['../namespaceCajita.html#adb928c073163bff90d4ca8a7d460fe18',1,'Cajita::particleGridMigrate(const LocalGridType &amp;local_grid, const ParticlePositions &amp;positions, const ParticleContainer &amp;src_particles, ParticleContainer &amp;dst_particles, const int min_halo_width, const bool force_migrate=false)'],['../namespaceCajita.html#af4371257b756699167df4544e4f2de13',1,'Cajita::particleGridMigrate(const LocalGridType &amp;local_grid, const ParticlePositions &amp;positions, ParticleContainer &amp;particles, const int min_halo_width, const bool force_migrate=false)']]],
  ['partition_5fview_567',['partition_view',['../classCajita_1_1DynamicPartitioner.html#ac74634de13e42e5b0ba1fdc245f0235a',1,'Cajita::DynamicPartitioner']]],
  ['partition_5fview_5fhost_568',['partition_view_host',['../classCajita_1_1DynamicPartitioner.html#a3fc797ab244839b768e68925a35937b3',1,'Cajita::DynamicPartitioner']]],
  ['performancetraits_569',['PerformanceTraits',['../classCabana_1_1Impl_1_1PerformanceTraits.html',1,'Cabana::Impl']]],
  ['periodic_570',['periodic',['../structCajita_1_1IndexConversion_1_1L2G.html#a467de8ddb7856a73d2a6d2b8626b7bfe',1,'Cajita::IndexConversion::L2G']]],
  ['permutation_571',['permutation',['../classCabana_1_1BinningData.html#a3bc243700d37b13d90ec156f9da8283d',1,'Cabana::BinningData::permutation()'],['../classCabana_1_1LinkedCellList.html#a02fc6f7e0664efa8c1af34b45d2c57f8',1,'Cabana::LinkedCellList::permutation()']]],
  ['permute_572',['permute',['../namespaceCabana.html#a02c3a57c3cd27a75094bbfa1be56145b',1,'Cabana::permute(const LinkedCellListType &amp;linked_cell_list, AoSoA_t &amp;aosoa, typename std::enable_if&lt;(is_linked_cell_list&lt; LinkedCellListType &gt;::value &amp;&amp;is_aosoa&lt; AoSoA_t &gt;::value), int &gt;::type *=0)'],['../namespaceCabana.html#a5a1ce7155c5c1185f46071b20d4dd332',1,'Cabana::permute(const LinkedCellListType &amp;linked_cell_list, SliceType &amp;slice, typename std::enable_if&lt;(is_linked_cell_list&lt; LinkedCellListType &gt;::value &amp;&amp;is_slice&lt; SliceType &gt;::value), int &gt;::type *=0)'],['../namespaceCabana.html#a824f296314f00ca8e121e6a26e2846db',1,'Cabana::permute(const BinningDataType &amp;binning_data, AoSoA_t &amp;aosoa, typename std::enable_if&lt;(is_binning_data&lt; BinningDataType &gt;::value &amp;&amp;is_aosoa&lt; AoSoA_t &gt;::value), int &gt;::type *=0)'],['../namespaceCabana.html#ab44a65c22331c71ed7cee721a41c54fc',1,'Cabana::permute(const BinningDataType &amp;binning_data, SliceType &amp;slice, typename std::enable_if&lt;(is_binning_data&lt; BinningDataType &gt;::value &amp;&amp;is_slice&lt; SliceType &gt;::value), int &gt;::type *=0)']]],
  ['pointer_5ftype_573',['pointer_type',['../classCabana_1_1Slice.html#a5c9d92c165481cc23048244992bd0eb0',1,'Cabana::Slice']]]
];
